### ISSUE TITLE
nodejs-tw 社群

### ISSUE THREAD

**Issue by zackexplosion** [y2468101216/node-wiki-gitbook#11]
https://github.com/nodejs-tw/nodejs-wiki-book

請問現在這邊的版本是從這邊 Clone 過來的嗎？ 原來的社群怎麼了呢？

**Comment by dca** [comment]
原有的因為年久失修，加上成員們各自有其它事務要處理。

這個版本的內容是來自社群版本沒錯，我這裡也可以協助把內容轉移到 nodejs-tw/nodejs-wiki-book

**Comment by zackexplosion** [comment]
想說是不是維護一份會比較輕鬆，畢竟社群的人力還是沒英語圈的人多

**Comment by y2468101216** [comment]
現在就維護這份就好，另外一邊有空再pr回去。畢竟我比較有空做這些事情，而且現在gitbook那邊是綁定這個目錄做sync。

**Comment by zackexplosion** [comment]
了解
