### ISSUE TITLE
跟進連結失效問題

### ISSUE THREAD

**Issue by tngan** [y2468101216/node-wiki-gitbook#12]
以下連結失效，需要跟進

BIBLIOGRAPHY.md
- Programming Node.js, April 2012 (est.), Travis Swicegood, Pragmatic Bookshelf
- Hands-on Node.js, The Node.js introduction and API reference, May 2011, Pedro Teixeira, LeanPub
- The Node Beginner Book, Manuel Kiessling
- Introduction To Node.js , Van Nguyen, CodeLesson

NODE_JAVASCRIPT.md
- `除了John Resig的那篇文章，Nicholas C. Zakas的 "Professional JavaScript for Web Developer 2nd edition" 有一個試閱本：http://yuiblog.com/assets/pdf/zakas-projs-2ed-ch18.pdf，598頁剛好也有簡短的說明)`

NODE_NPM.md
- http://search.npmjs.org/  (在[這裡](https://github.com/y2468101216/node-wiki-gitbook/blob/master/NODE_NPM.md#使用-npm-安裝套件))

**Comment by zackexplosion** [comment]
現在搜尋功能好像改到首頁了 https://www.npmjs.com/

**Comment by tngan** [comment]
是的，還有這個 http://npm-stat.com/ 可以搜尋統計數據。

**Comment by y2468101216** [comment]
可以的話麻煩各位幫忙更改，我最近在忙著做todo_list。

**Comment by tngan** [comment]
我跑了 PR， @y2468101216  看看有沒有問題。更改如下：

**刪除連結**
- Programming Node.js, April 2012 (est.): 找不到相關資料
- Introduction To Node.js: CodeLesson 再沒有提供課程了
- Professional JavaScript for Web Developer 2nd edition: 找不到相關資料

其餘有問題的連結我都已經更新。
