### ISSUE TITLE
APPENDIX(附錄)

### ISSUE THREAD

**Issue by y2468101216** [y2468101216/node-wiki-gitbook#16]
跟node.js沒有那麼相關的可以擺在本頁中

**Comment by tngan** [comment]
@y2468101216 這句規範可以移去 README.md 的根目錄結構 ?

**Comment by y2468101216** [comment]
OK

2015-10-29 16:18 GMT+08:00 Tony Ngan notifications@github.com:

**Comment by tngan** [comment]
See 7c642795b0e0768db4a6b5934ba83601c77f686a
