### ISSUE TITLE
NODE_ES6.md

### ISSUE THREAD

**Issue by y2468101216** [y2468101216/node-wiki-gitbook#2]
需要使用過nodeV4的人幫忙撰寫這條目，說明V4支援哪些ES6語法。

**Comment by tngan** [comment]
初稿已完成。有一部分 ES6 的語法 NodeJS 還未有整合，這份文檔會不停更新。

**Comment by y2468101216** [comment]
十分感謝。

Yun上

2015-09-29 16:29 GMT+08:00 Tony Ngan notifications@github.com:

**Comment by y2468101216** [comment]
我看完了，我想Staged features跟In progress features就別寫了，建議結語的連結可以移到參考資料。

**Comment by tngan** [comment]
參考資料是指 BIBLIOGRAPHY.md ?

**Comment by y2468101216** [comment]
你看NODE_EXPRESS跟NODE_EXPRESS_VIEW下面都有個原始資料或參考資料。

2015-09-30 10:42 GMT+08:00 Tony Ngan notifications@github.com:

**Comment by tngan** [comment]
已加參考資料

**Comment by dca** [comment]
小聲建議應該走個 PR

**Comment by y2468101216** [comment]
PR是啥

**Comment by tngan** [comment]
@dca 是指 pull request ?
