### ISSUE TITLE
NODE_INSTALL.md

### ISSUE THREAD

**Issue by y2468101216** [y2468101216/node-wiki-gitbook#5]
我想全面改成只用nvm，大家看法如何？4板以後切換版本變得很重要

**Comment by tngan** [comment]
我今早看這個 markdown 有同一個想法, 但有一個問題，我現在是用 nvm 切換版本的，但每次切換後重新開 terminal，node 都是用最新的，看來要找個方法設定預設的版本

**Comment by y2468101216** [comment]
其實你打nvm裡面就有example說如何set default。

 nvm alias default 0.10.32

**Comment by tngan** [comment]
感謝。
