### ISSUE TITLE
NODE_BASIC.md

### ISSUE THREAD

**Issue by tngan** [y2468101216/node-wiki-gitbook#6]
可以補充如何設置 HTTPS 伺服器嗎 ?

**Comment by y2468101216** [comment]
可以是可以，但有點微妙，因為node.js本身就是server了

**Comment by dca** [comment]
HTTPS 就是要加個憑證，這個東西經常需要但卻不影響學習，推薦可以寫到附錄

**Comment by y2468101216** [comment]
錯看成http了ORZ，擺附錄吧

**Comment by tngan** [comment]
@y2468101216 附錄是指 NODE_JAVASCRIPT.md 這個嗎 ?

**Comment by y2468101216** [comment]
我增加了附錄頁面，在那邊做新增吧。另外我不確定APPENDIX這個單字是否就是附錄的意思，有需要可以更改。

**Comment by tngan** [comment]
@y2468101216 @dca 
還是把這個連結放在 NODE_BASIC 的參考資料 ?
https://nodejs.org/api/https.html

**Comment by y2468101216** [comment]
也可，我有開一個APPENDIX(附錄)，可以考慮放在那邊。
