### ISSUE TITLE
Nodejs 統一寫法

### ISSUE THREAD

**Issue by zackexplosion** [y2468101216/node-wiki-gitbook#7]
文章看到 Node.js node.js  nodeJS 三種寫法，不是統一寫法會比較好閱讀呢?

![node-wiki-gitbook_node_basic_md_at_master_ _y2468101216_node-wiki-gitbook](https://cloud.githubusercontent.com/assets/5180966/10478163/18f30e80-728e-11e5-99e9-c39fb847fcdc.png)

**Comment by tngan** [comment]
官方 (https://nodejs.org/en/) 是用 Node.js，建議就用這個吧。
